use std::fs::File;
use std::io::{BufRead, BufReader, Write};
use std::path::Path;
use std::sync::RwLock;
use std::time::{SystemTime, UNIX_EPOCH};

use reqwest::header::HeaderValue;
use url::Url;

use crate::error::AppError;

#[derive(Clone, Debug)]
struct StoredCookie {
    domain: String,
    include_subdomains: bool,
    path: String,
    secure: bool,
    expiry: Option<u64>,
    name: String,
    value: String,
    http_only: bool,
    host_only: bool,
}

/// Netscape-format cookie jar that also implements reqwest's CookieStore.
#[derive(Debug, Default)]
pub struct CookieJar {
    cookies: RwLock<Vec<StoredCookie>>,
}

impl CookieJar {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn load_netscape(&self, path: &Path) -> Result<(), AppError> {
        let file = File::open(path).map_err(|e| {
            AppError::InvalidArgument(format!(
                "could not read cookie file {}: {e}",
                path.display()
            ))
        })?;
        let reader = BufReader::new(file);
        let mut loaded = Vec::new();
        let now = now_unix();
        for line in reader.lines() {
            let line = line?;
            if let Some(cookie) = parse_netscape_line(&line)
                && cookie.expiry.is_none_or(|exp| exp > now)
            {
                loaded.push(cookie);
            }
        }
        *self.cookies.write().expect("cookie lock") = loaded;
        Ok(())
    }

    pub fn save_netscape(&self, path: &Path) -> Result<(), AppError> {
        if let Some(parent) = path.parent().filter(|p| !p.as_os_str().is_empty()) {
            std::fs::create_dir_all(parent)?;
        }
        let mut file = File::create(path)?;
        writeln!(file, "# Netscape HTTP Cookie File")?;
        writeln!(file, "# Generated by rtget")?;
        let now = now_unix();
        let cookies = self.cookies.read().expect("cookie lock");
        for c in cookies.iter() {
            if c.expiry.is_some_and(|exp| exp <= now) {
                continue;
            }
            let domain = if c.http_only {
                format!("#HttpOnly_{}", c.domain)
            } else {
                c.domain.clone()
            };
            let flag = if c.include_subdomains {
                "TRUE"
            } else {
                "FALSE"
            };
            let secure = if c.secure { "TRUE" } else { "FALSE" };
            let exp = c.expiry.unwrap_or(0);
            writeln!(
                file,
                "{domain}\t{flag}\t{}\t{secure}\t{exp}\t{}\t{}",
                c.path, c.name, c.value
            )?;
        }
        Ok(())
    }
}

impl reqwest::cookie::CookieStore for CookieJar {
    fn set_cookies(&self, cookie_headers: &mut dyn Iterator<Item = &HeaderValue>, url: &Url) {
        let mut guard = self.cookies.write().expect("cookie lock");
        for value in cookie_headers {
            let Ok(raw) = value.to_str() else {
                continue;
            };
            if let Some(cookie) = parse_set_cookie(raw, url) {
                guard.retain(|c| {
                    !(c.name == cookie.name
                        && domain_eq(&c.domain, &cookie.domain)
                        && c.path == cookie.path)
                });
                if cookie.expiry.is_none_or(|exp| exp > now_unix()) {
                    guard.push(cookie);
                }
            }
        }
    }

    fn cookies(&self, url: &Url) -> Option<HeaderValue> {
        let guard = self.cookies.read().expect("cookie lock");
        let now = now_unix();
        let mut parts = Vec::new();
        for c in guard.iter() {
            if cookie_matches(c, url, now) {
                parts.push(format!("{}={}", c.name, c.value));
            }
        }
        if parts.is_empty() {
            None
        } else {
            HeaderValue::from_str(&parts.join("; ")).ok()
        }
    }
}

fn parse_netscape_line(line: &str) -> Option<StoredCookie> {
    let line = line.trim();
    if line.is_empty() || (line.starts_with('#') && !line.starts_with("#HttpOnly_")) {
        return None;
    }
    let http_only = line.starts_with("#HttpOnly_");
    let line = line.strip_prefix("#HttpOnly_").unwrap_or(line);
    let cols: Vec<&str> = line.split('\t').collect();
    if cols.len() < 7 {
        return None;
    }
    let domain = cols[0].to_string();
    let include_subdomains = cols[1].eq_ignore_ascii_case("TRUE");
    let path = cols[2].to_string();
    let secure = cols[3].eq_ignore_ascii_case("TRUE");
    let expiry: u64 = cols[4].parse().unwrap_or(0);
    Some(StoredCookie {
        host_only: !include_subdomains && !domain.starts_with('.'),
        domain,
        include_subdomains,
        path,
        secure,
        expiry: if expiry == 0 { None } else { Some(expiry) },
        name: cols[5].to_string(),
        value: cols[6].to_string(),
        http_only,
    })
}

fn parse_set_cookie(header: &str, url: &Url) -> Option<StoredCookie> {
    let mut parts = header.split(';');
    let nv = parts.next()?.trim();
    let (name, value) = nv.split_once('=')?;
    if name.trim().is_empty() {
        return None;
    }
    let mut cookie = StoredCookie {
        domain: url.host_str()?.to_string(),
        include_subdomains: false,
        path: default_cookie_path(url),
        secure: false,
        expiry: None,
        name: name.trim().to_string(),
        value: value.trim().to_string(),
        http_only: false,
        host_only: true,
    };
    for attr in parts {
        let attr = attr.trim();
        if attr.is_empty() {
            continue;
        }
        let (key, val) = match attr.split_once('=') {
            Some((k, v)) => (k.trim(), Some(v.trim())),
            None => (attr, None),
        };
        match key.to_ascii_lowercase().as_str() {
            "domain" => {
                if let Some(d) = val.filter(|s| !s.is_empty()) {
                    let d = d.strip_prefix('.').unwrap_or(d);
                    cookie.domain = format!(".{d}");
                    cookie.include_subdomains = true;
                    cookie.host_only = false;
                }
            }
            "path" => {
                if let Some(p) = val.filter(|s| !s.is_empty()) {
                    cookie.path = p.to_string();
                }
            }
            "secure" => cookie.secure = true,
            "httponly" => cookie.http_only = true,
            "max-age" => {
                if let Some(secs) = val.and_then(|s| s.parse::<i64>().ok()) {
                    if secs <= 0 {
                        cookie.expiry = Some(now_unix().saturating_sub(1));
                    } else {
                        cookie.expiry = Some(now_unix().saturating_add(secs as u64));
                    }
                }
            }
            _ => {}
        }
    }
    Some(cookie)
}

fn default_cookie_path(url: &Url) -> String {
    let path = url.path();
    if let Some(i) = path.rfind('/') {
        let dir = &path[..=i];
        if dir.is_empty() {
            "/".into()
        } else {
            dir.into()
        }
    } else {
        "/".into()
    }
}

fn cookie_matches(cookie: &StoredCookie, url: &Url, now: u64) -> bool {
    if cookie.expiry.is_some_and(|exp| exp <= now) {
        return false;
    }
    if cookie.secure && url.scheme() != "https" {
        return false;
    }
    let Some(host) = url.host_str() else {
        return false;
    };
    if !domain_matches(cookie, host) {
        return false;
    }
    path_matches(&cookie.path, url.path())
}

fn domain_matches(cookie: &StoredCookie, host: &str) -> bool {
    let host = host.trim_end_matches('.').to_ascii_lowercase();
    let domain = cookie
        .domain
        .trim_start_matches('.')
        .trim_end_matches('.')
        .to_ascii_lowercase();
    if cookie.host_only || !cookie.include_subdomains {
        return host == domain;
    }
    host == domain || host.ends_with(&format!(".{domain}"))
}

fn domain_eq(a: &str, b: &str) -> bool {
    a.trim_start_matches('.')
        .eq_ignore_ascii_case(b.trim_start_matches('.'))
}

fn path_matches(cookie_path: &str, url_path: &str) -> bool {
    let path = if url_path.is_empty() { "/" } else { url_path };
    if cookie_path == "/" {
        return true;
    }
    path == cookie_path
        || (path.starts_with(cookie_path)
            && (cookie_path.ends_with('/')
                || path.as_bytes().get(cookie_path.len()) == Some(&b'/')))
}

fn now_unix() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use std::sync::Arc;

    #[test]
    fn netscape_roundtrip_and_match() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("cookies.txt");
        let mut f = File::create(&path).unwrap();
        writeln!(f, ".example.com\tTRUE\t/\tFALSE\t9999999999\tsession\tabc").unwrap();
        drop(f);

        let jar = CookieJar::new();
        jar.load_netscape(&path).unwrap();
        let url = Url::parse("http://www.example.com/file").unwrap();
        let header = reqwest::cookie::CookieStore::cookies(&jar, &url).unwrap();
        assert_eq!(header.to_str().unwrap(), "session=abc");

        let other = Url::parse("http://evil.test/").unwrap();
        assert!(reqwest::cookie::CookieStore::cookies(&jar, &other).is_none());

        let out = dir.path().join("out.txt");
        jar.save_netscape(&out).unwrap();
        let text = std::fs::read_to_string(&out).unwrap();
        assert!(text.contains("session\tabc"));
    }

    #[test]
    fn set_cookie_from_response() {
        let jar = CookieJar::new();
        let url = Url::parse("https://files.example.com/dl").unwrap();
        let value = HeaderValue::from_static("id=42; Domain=example.com; Path=/; Secure");
        reqwest::cookie::CookieStore::set_cookies(&jar, &mut std::iter::once(&value), &url);
        let header = reqwest::cookie::CookieStore::cookies(&jar, &url).unwrap();
        assert_eq!(header.to_str().unwrap(), "id=42");
        let _ = Arc::new(jar);
    }
}
